<%@ Page Title="" Language="C#" MasterPageFile="~/Placer_Viajes.Master" AutoEventWireup="true" CodeBehind="Reserva.aspx.cs" Inherits="Capa_de_presentacion.Reserva" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 112px;
            text-align: left;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Su Reserva</h1>
    <asp:GridView ID="grv_reserva" runat="server" CssClass="table" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowDeleting="grv_reserva_RowDeleting">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:BoundField DataField="paquete_turistico.id_paquete_turistico" HeaderText="ID" ReadOnly="true"></asp:BoundField>
            <asp:BoundField DataField="paquete_turistico.nombre_paquete" HeaderText="Nombre Paquete" ReadOnly="True" />
            <asp:BoundField DataField="paquete_turistico.destino.nombre" HeaderText="Destino" ReadOnly="True" />
            <asp:BoundField DataField="paquete_turistico.alojamiento.habitacion.nombre" HeaderText="Pieza" />
            <asp:BoundField DataField="paquete_turistico.precio_mayores" HeaderText="Precio Unitario" DataFormatString="{0:c}" ReadOnly="True" />
            <asp:BoundField DataField="paquete_turistico.precio_menores" HeaderText="Precio Unitario Menores" DataFormatString="{0:c}" ReadOnly="true"/>
            <asp:TemplateField HeaderText="Cantidad Mayores">
                <ItemTemplate>
                    <asp:TextBox ID="txt_cantidad_mayores" runat="server" MaxLength="1"></asp:TextBox>
                    <asp:RegularExpressionValidator ID="rev_cantidad_mayores" runat="server" ControlToValidate="txt_cantidad_mayores" Text="*" ErrorMessage="La cantidad de mayores es numérica" CssClass="alert-danger" ValidationExpression="^\d+$"></asp:RegularExpressionValidator>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Debe ingresar la cantidad de mayores que viajarán" ControlToValidate="txt_cantidad_mayores" Text="*" CssClass="alert-danger"></asp:RequiredFieldValidator>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Cantidad Menores">
                <ItemTemplate>
                    <asp:TextBox ID="txt_cantidad_menores" runat="server" MaxLength="1"></asp:TextBox>
                    <asp:RegularExpressionValidator ID="rev_cantidad_menores" runat="server" text="*" ControlToValidate="txt_cantidad_menores" ErrorMessage="La cantidad de menores es numérica" CssClass="alert-danger" ValidationExpression="^\d+$"></asp:RegularExpressionValidator>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="Debe ingresar la cantidad de menores que viajarán" ControlToValidate="txt_cantidad_menores" Text="*" CssClass="alert-danger"></asp:RequiredFieldValidator>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <SortedAscendingCellStyle BackColor="#FDF5AC" />
        <SortedAscendingHeaderStyle BackColor="#4D0000" />
        <SortedDescendingCellStyle BackColor="#FCF6C0" />
        <SortedDescendingHeaderStyle BackColor="#820000" />
    </asp:GridView>
    <br />
     <br />
    <table class="nav-justified">
        <tr>
            <td class="auto-style1"><asp:Label ID="Label1" runat="server" Text="Fecha de viaje: "></asp:Label></td>
            <td class="text-left">
                <asp:TextBox ID="txt_fecha_viaje" runat="server" CssClass="datepicker"></asp:TextBox>
                <script type="text/javascript">
                    $(document).ready(
                        function () {

                            $('.datepicker').datepicker({
                                dateFormat: "dd/mm/yy",
                                monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
                                dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"], minDate: "-0D", defaultDate: "+0D"
                            });
                        }
                        );
                    </script>
            </td>

        </tr>
    </table>
    
    <br />
    <br />
    <asp:ValidationSummary ID="ValidationSummary1" runat="server" HeaderText="Han Ocurrido los siguientes errores" CssClass="alert-danger" />
    <asp:Button ID="btn_reservar" runat="server" Text="Reservar" OnClick="btn_reservar_Click" />
&nbsp;&nbsp;&nbsp;
    <asp:Button ID="btn_volver" runat="server" OnClick="btn_cancelar_Click" Text="Volver" CausesValidation="false" />
</asp:Content>
